name: Build and test main JDK versions

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        java: [11, 17, 18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Free disk space
        run: |
          echo "Removing large unused packages"
          sudo apt-get remove -y azure-cli google-cloud-sdk microsoft-edge-stable google-chrome-stable powershell mono-devel >/dev/null 2>&1
          sudo apt-get autoclean -y >/dev/null 2>&1
          sudo apt-get clean -y >/dev/null 2>&1
          sudo apt-get autoremove -y >/dev/null 2>&1
          echo "Removing large unused files/directories"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /usr/local/lib/node_modules /usr/local/share/powershell /usr/local/share/chromium
          sudo rm -rf /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY" /usr/local/graalvm /usr/local/.ghcup
          sudo df -h
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          check-latest: true
      - uses: gradle/gradle-build-action@v2
      - name: Test with Gradle
        run: ./gradlew test
        timeout-minutes: 60

